### ISSUE TITLE
AmqpHandler - should not use sync over async in Constructor

### ISSUE THREAD

**Issue by jonnybee** [ks-no/fiks-io-client-dotnet#101]
AmqpHandler calls SetupConnectionFactory from constructor and this mehod calls an async method with .Result
This may cause deadlock to occur and there are ways to make this code much better. 

````
        private void SetupConnectionFactory(IntegrasjonConfiguration integrasjonConfiguration)
        {
            try
            {
                var maskinportenToken = _maskinportenClient.GetAccessToken(integrasjonConfiguration.Scope).Result;
                _connectionFactory.UserName = integrasjonConfiguration.IntegrasjonId.ToString();
                _connectionFactory.Password = $"{integrasjonConfiguration.IntegrasjonPassord} {maskinportenToken.Token}";
            }
            catch (AggregateException ex)
            {
                throw new FiksIOAmqpSetupFailedException("Unable to setup connection factory.", ex);
            }
        }
````

See: [https://blog.stephencleary.com/2013/01/async-oop-2-constructors.html](https://blog.stephencleary.com/2013/01/async-oop-2-constructors.html)

You should also not need to handle AggregateException in the code.

**Comment by jarleborsheim** [comment]
Hi @jonnybee! 

We have released a new version of the client that should fix this problem.
The new version (2.0.0) is breaking since it now demands that you use the CreateAsync method for creating a FiksIOClient.
We are closing this issue then, but let us know if there is more to be done. 
Thanks for contributing in this repository!
