### ISSUE TITLE
FiksIOClient - make connections more resilient when listening for incoming messages

### ISSUE THREAD

**Issue by jonnybee** [ks-no/fiks-io-client-dotnet#105]
Hi, 

We have sometimes experienced that the MQ connection is lost and as-is the only resolution is to restart the application/webservice that contains the listener. We have experienced similar issues earlier in internal applications and found a way to make the connection more resilient by implementing a timer function that checks if the connection is Open and when not do a reconnect. 

If you are interested I can make a PR for the changes to create a timer that checks if the mq connection is open and if not will make a reconnect. 

W have made a private build of FiksIOClient to try this is out in production and the client has automatically reconnected these times in the last 2 weeks:
![image](https://user-images.githubusercontent.com/3512406/190605665-0bb963ba-2893-4c6c-8298-90834b8fa92a.png)

**Comment by jarleborsheim** [comment]
We're looking into this. Thanks for contributing!

**Comment by jarleborsheim** [comment]
Hi @jonnybee!

I used your pull-request as a base for [this one](https://github.com/ks-no/fiks-io-client-dotnet/pull/107). We will add this feature as a configurable keepAlive. It is by default not activated then.

It is a bit strange this with it loosing connection this often. We would love to try to figure out why. Could you send id for your Fiks-IO account in prod/test where you're seeing these connections are lost? You can send it to me on Slack or by e-mail. Also if you could send me time and date recently when you're seeing these connection losses. Then I will have a look at our side.

We had a similar issue with our "protokoll validator" earlier. It would loose its connection from time to time, and a restart would fix it. Typically if it did not receive any messages in a while. We did some small changes to the code that was using the FiksIOClient for listening for messages and as far as I can tell it hasn't had any problems since. I think one of the tricks was to have it running as a BackgroundService, but we did some other tweaks too.  https://github.com/ks-no/fiks-protokoll-validator/blob/main/api/KS.FiksProtokollValidator.WebAPI/FiksIO/FiksResponseMessageService.cs

**Comment by jarleborsheim** [comment]
@jonnybee A new version ([2.0.1](https://www.nuget.org/packages/KS.Fiks.IO.Client)) is now out that has this feature. We also included an IsOpen() method for those that want to check the status and do something with connection loss themselves.

**Comment by jarleborsheim** [comment]
Closing this issue since it should be fixed with the latest release
